apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deploy
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image:  docfahad/synapse:api-gateway
          imagePullPolicy: Always
          volumeMounts:
          - name: tz-config
            mountPath:  /etc/localtime
      volumes:
       - name: tz-config
         hostPath:
              path: /usr/share/zoneinfo/Europe/London
              type: File