apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-api-service
spec:
  type: NodePort #LoadBalancer #
  selector:
    app: gatekeeper-api
  ports:
    - name: gatekeeper-api-service
      protocol: TCP
      port: 7090
      targetPort: 8080
      #nodePort: 32000