apiVersion: v1
kind: Service
metadata:
  name: pick-job-assigner-api-np-service
spec:
  type: NodePort #LoadBalancer #
  selector:
    app: pick-job-assigner-api
  ports:
    - name: pick-job-assigner-api-np-service
      protocol: TCP
      port: 7070
      targetPort: 8080
      #nodePort: 32000