apiVersion: apps/v1
kind: Deployment
metadata:
  name: pick-message-consumer-deploy
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: pick-message-consumer
  template:
    metadata:
      labels:
        app: pick-message-consumer
    spec:
      containers:
        - name: pick-message-consumer
          image:  docfahad/synapse:pick-message-consumer 