apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    #path: /run/desktop/mnt/host/c/storage/rabbit-ques
    path: /mnt/rabbit-ques
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - synapse-worker-pool-687c9f4a-xx2qg
