apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    #RABBITMQ_MNESIA_DIR=/queues/data
    #RABBITMQ_LOG_BASE=/queues/data
    loopback_users.guest = false
    log.console = true
